server:
  port: 9291

spring:
  application:
    name: STOCK-QUERY
  data:
    mongodb:
      host: localhost
      port: 27017
      database: stock_cqrs
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://database-e-stock-market.cphelrjqqlbg.us-east-2.rds.amazonaws.com:3306/stock_cqrs
    username: root
    password: s09c12s09c12
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://ec2-3-138-245-147.us-east-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: springbankSigningKey
