spring:
  application:
    name: STOCK-COMMAND


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://ec2-3-138-245-147.us-east-2.compute.amazonaws.com:8761/eureka/
  instance:
    hostname: localhost