spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - content-type
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
              - HEAD
              - DELETE
      routes:
        - id: company-service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/api/v1.0/market/company/**
        - id: stock-service
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/v1.0/market/stock/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 8989